### ISSUE TITLE
Juzi Bot功能优化

### ISSUE THREAD

**Issue by AquaIndigo** [juzibot/intern#10]
## 苏尧-期初报告

> 部门：Juzi AI LAB
> 汇报人：@苏尧 
> 导师：@Qinghua Duan 
> 时间：11月21日

工作内容
--
时间 | 重点工作 | 关键进展
-- | -- | --
11月1日-11月7日 | 添加关键词搜索功能，对文本/论文摘要提取关键词做tags | 实现了中英文文本关键词提取的功能，并且可以自动识别，提供相应接口
11月8日-11月14日 | 测试现有text-vectorize做关键词提取的效果 研究keyBERT库 | 通过比较全面的测试，找到了一组比较好的模型和参数
11月15日-11月21日 | 中文关键词提取的算法优化 Image Caption文献综述 | 完成zhkeybert这个用来做中文关键词抽取的python库https://github.com/deepdialog/ZhKeyBERT
11月22日-11月28日 | Image Caption算法优化 Image Caption实现优化 | 更新Image Caption的服务 更新JuziBot的相关功能

**Comment by socialok** [comment]
请回复对应的周报在自己的导师对应项目的对应issue上面
