### ISSUE TITLE
5G消息项目进度

### ISSUE THREAD

**Issue by Bibabo-BUPT** [juzibot/intern#8]
**日期：2021年11月21日**
**本周完成的成果：**

- 学习了解部分Wechaty API接口

- 安装安卓模拟器和终端测试消息app

**本周遇到的困难和需要配合的地方**：

- 解决IOS系统无法进行API接口测试问题

**下周的开发计划和预计成果：**

- 继续学习Wechaty API接口

- 利用公用账号进行API接口测试，熟悉5G接口

**其他需要说明和同步的事项：**
无

**Comment by socialok** [comment]
请回复对应的周报在自己的导师对应项目的对应issue上面
