### ISSUE TITLE
JuziBot 中文关键词提取

### ISSUE THREAD

**Issue by AquaIndigo** [juzibot/intern#9]
# [项目名称] 进度报告

日期：2021-11-21

## 本周完成的成果

1. 完成了zhkeybert这个用于中文关键词抽取的python库
2. 更新了相关的服务和JuziBot的功能
3. 做了一些关于Image Captioning的文献综述

## 本周遇到的困难和需要配合的地方

1. 读文献有些困难，看得比较慢

## 下周的开发计划和预计成果

1. 完成Image Caption相关的算法优化和机器人的功能实现

## 其他需要说明和同步的事项

1. 暂无

**Comment by socialok** [comment]
请回复对应的周报在自己的导师对应项目的对应issue上面
